# TCL File Generated by Component Editor 13.0
# Wed Sep 28 15:41:44 GMT+08:00 2016
# DO NOT MODIFY


# 
# oc_iic "oc_iic" v1.0
# xiaomeige 2016.09.28.15:41:44
# 
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module oc_iic
# 
set_module_property DESCRIPTION ""
set_module_property NAME oc_iic
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP CoreCourse
set_module_property AUTHOR xiaomeige
set_module_property DISPLAY_NAME oc_iic
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL oc_i2c_master
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file oc_i2c_master.v VERILOG PATH oc_i2c_master.v TOP_LEVEL_FILE
add_fileset_file i2c_master_bit_ctrl.vhd VHDL PATH i2c_master_bit_ctrl.vhd
add_fileset_file i2c_master_byte_ctrl.vhd VHDL PATH i2c_master_byte_ctrl.vhd
add_fileset_file i2c_master_top.vhd VHDL PATH i2c_master_top.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point av
# 
add_interface av avalon end
set_interface_property av addressUnits WORDS
set_interface_property av associatedClock clock_sink
set_interface_property av associatedReset reset_sink
set_interface_property av bitsPerSymbol 8
set_interface_property av burstOnBurstBoundariesOnly false
set_interface_property av burstcountUnits WORDS
set_interface_property av explicitAddressSpan 0
set_interface_property av holdTime 0
set_interface_property av linewrapBursts false
set_interface_property av maximumPendingReadTransactions 0
set_interface_property av readLatency 0
set_interface_property av readWaitTime 1
set_interface_property av setupTime 0
set_interface_property av timingUnits Cycles
set_interface_property av writeWaitTime 0
set_interface_property av ENABLED true
set_interface_property av EXPORT_OF ""
set_interface_property av PORT_NAME_MAP ""
set_interface_property av SVD_ADDRESS_GROUP ""

add_interface_port av av_address address Input 3
add_interface_port av av_chipselect chipselect Input 1
add_interface_port av av_write write Input 1
add_interface_port av av_read read Input 1
add_interface_port av av_writedata writedata Input 8
add_interface_port av av_readdata readdata Output 8
add_interface_port av av_waitrequest_n waitrequest_n Output 1
set_interface_assignment av embeddedsw.configuration.isFlash 0
set_interface_assignment av embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment av embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment av embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink av_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink av_reset reset Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint av
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender av_irq irq Output 1


# 
# connection point wire
# 
add_interface wire conduit end
set_interface_property wire associatedClock clock_sink
set_interface_property wire associatedReset reset_sink
set_interface_property wire ENABLED true
set_interface_property wire EXPORT_OF ""
set_interface_property wire PORT_NAME_MAP ""
set_interface_property wire SVD_ADDRESS_GROUP ""

add_interface_port wire scl_pad_io export Bidir 1
add_interface_port wire sda_pad_io export Bidir 1

